### ISSUE TITLE
Feature request: packaging of misp-stix on PyPi

### ISSUE THREAD

**Issue by 2xyo** [MISP/misp-stix#11]
It would be great to have `misp-stix` packaged on https://pypi.org/ to facilitate its use in other projects.

**Comment by chrisr3d** [comment]
This is totally part of the plan once the STIX -> MISP import feature is fully implemented, functional and can replace the old current implementation on MISP

**Comment by mavam** [comment]
Just +1'ing this request. Even if this is still WIP, it would be great to have it on PyPI so that we can get more coverage. I'm preparing a package that uses misp-stix, but I'm struggling with correctly mentioning the project in the `install_requires` section of my setup.cfg. Any advice how to reference this project there?

There is no `misp-stix` on PyPI, but this is in your pyproject.toml:

```toml
[tool.poetry]
name = "misp_stix_converter"
```

The reference `misp_stix_converter` unfortunately points to the old converter: https://pypi.org/project/misp-stix-converter/#history. 


This is what I have currently:

```toml
[options]
install_requires =
    misp_stix_converter @ git+https://github.com/misp/misp-stix@v2.4.160
```

I've been trying to upload my package via `twine upload -r testpypi dist/*`. But this errors with:

```
Invalid value for requires_dist. Error: Can't have direct dependency: 'misp-stix-converter
         @ git+https://github.com/misp/misp-stix@v2.4.160'
```

I'm not an expert, but my conclusion is that it looks like I'm blocked uploading my package until you published yours?

**Comment by ThisIsNotTheUserYouAreLookingFor** [comment]
@mavam that is correct, there is a way to publish your own package if you really want it by copying the source in your own package and reference to your local source. I would advise against it, as you won't stay up to date on latest changes to this repo though :)

**Comment by maciej-lech** [comment]
Hi!

v2.4.163 and v2.4.168 are mining on pypi. Is there any plan to upload them?
Installing from git is less efficient when it comes to pip cache and has other problems.

Best regards,
Maciej Lech
